// Interop parity: the files that tell OTHER agents how to work with the data must
// say the same thing as the code. These checks fail when one of them drifts.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { AGENTS_SNIPPET_BODY, STATUSES } from '../lib/store.mjs';

const here = path.dirname(fileURLToPath(import.meta.url));
const repo = path.join(here, '..', '..', '..');
const plugin = path.join(here, '..');
const read = (p) => readFileSync(p, 'utf8').replace(/\r\n/g, '\n');

test('interop/AGENTS.md carries exactly the block --seed-agents writes', () => {
  const doc = read(path.join(repo, 'interop', 'AGENTS.md'));
  assert.ok(doc.includes(AGENTS_SNIPPET_BODY), 'interop/AGENTS.md is generated by scripts/release-sync.mjs from AGENTS_SNIPPET_BODY; run it after editing the snippet');
});

test('the Codex prompt names every MCP tool and every field an agent must act on', () => {
  const doc = read(path.join(repo, 'interop', 'codex', 'feedback.md'));
  const mcp = read(path.join(plugin, 'bin', 'feedback-studio-mcp.mjs'));
  const tools = [...mcp.matchAll(/^\s+name: '([a-z_]+)',$/gm)].map((m) => m[1]);
  assert.ok(tools.length >= 6, 'found the tool list in the MCP server');
  for (const t of tools) assert.ok(doc.includes('`' + t + '`'), 'Codex prompt names the tool ' + t);
  for (const field of ['edits', 'textEdit', 'imageReplace', 'variants', 'pick', 'autonomy', 'shot', 'via: "narration"', 'question', 'sourceFile']) {
    assert.ok(doc.includes(field), 'Codex prompt explains ' + field);
  }
  for (const s of STATUSES) assert.ok(doc.includes('`' + s + '`'), 'Codex prompt names the status ' + s);
});

test('hooks.json wires the three hooks to report.mjs with the right modes', () => {
  const hooks = JSON.parse(read(path.join(plugin, 'hooks', 'hooks.json'))).hooks;
  const cmdOf = (event) => hooks[event][0].hooks[0].command;
  assert.match(hooks.PostToolUse[0].matcher, /Edit\|Write/);
  assert.match(cmdOf('PostToolUse'), /\$\{CLAUDE_PLUGIN_ROOT\}\/hooks\/report\.mjs" edit$/);
  assert.match(cmdOf('UserPromptSubmit'), /report\.mjs" prompt$/);
  assert.match(cmdOf('Stop'), /report\.mjs" idle$/);
  for (const event of ['PostToolUse', 'UserPromptSubmit', 'Stop']) {
    const t = hooks[event][0].hooks[0].timeout;
    assert.ok(Number.isInteger(t) && t <= 5, event + ' hook times out within a few seconds (the value is in seconds)');
  }
  // The script accepts exactly these three modes.
  const src = read(path.join(plugin, 'hooks', 'report.mjs'));
  for (const mode of ['edit', 'prompt', 'idle']) assert.ok(src.includes("'" + mode + "'"), 'report.mjs handles mode ' + mode);
});
